name: Deployment of current GitHub repo on a server through SSH
on:
  push:
    branches: [main, develop]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: Rxinui/ssh-deploy-repo-action@v1
        with:
          # Required
          ssh-user: ${{ secrets.USER }}
          ssh-password: ${{ secrets.PASSWORD }}
          ssh-domain: ${{ secrets.DOMAIN }}
          # Optional
          git-clone-by: ssh
          target-branch: develop
          target-directory: /var/www/html/pgrimaud/
